### ISSUE TITLE
Repo needs LICENSE, CoC, Contributing docs

### ISSUE THREAD

**Issue by ascasson** [cbtnuggets/lib-client-gg-collaborate-js#3]
Currently this project is not assigned an open license, which means the project receives default copyright laws. Legally, a license must be applied.

Additional docs to match CBT Nuggets-oriented projects also need to be included. See the LICENSE, Code of Conduct and Contributing docs in this example repo: https://github.com/cbtnuggets/lib-client-gg-js

**Comment by scmilee** [comment]
pr #4 solves this

**Comment by ascasson** [comment]
Sweet! Thanks!
